// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Runtime sanity checks to surface common misconfiguration (helps debug "Failed to fetch")
if (!SUPABASE_URL) {
  // eslint-disable-next-line no-console
  console.error('[supabase] VITE_SUPABASE_URL is not defined. Requests will fail. Check your .env and restart the dev server.');
}
if (!SUPABASE_PUBLISHABLE_KEY) {
  // eslint-disable-next-line no-console
  console.error('[supabase] VITE_SUPABASE_PUBLISHABLE_KEY is not defined. Authentication will fail.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});